trigger:
  - OTP-*
pool: 'TJP'
#vmImage: 'ubuntu latest'
steps:
  - task: DownloadSecureFile@1
    name: settingsxml
    inputs:
      secureFile: settings-security.xml

  - bash: cp -p $(settingsxml.secureFilePath) /tmp/settings-security.xml
  - task: Maven@3
    inputs:
      goals: 'clean package'
      options: '-Pjunit-report --settings docker-build/azure-deploy/settings.xml -Dsettings.security=/tmp/settings-security.xml -B -U'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx1G' # Build agents are limited to 2Gb
