# Pipeline for after pull request has been approved and development branch has been merged to release branch
trigger:
  - resesok-otp
pool: 'TJP'
variables:
  - name: otpVersion

steps:
  - checkout: self
    persistCredentials: false

  - task: DownloadSecureFile@1
    displayName: 'Copy Maven authorization for Skånetrafiken Maven repository'
    name: settingsSecurity
    inputs:
      secureFile: settings-security.xml

  - bash: cp -p $(settingsSecurity.secureFilePath) /tmp/settings-security.xml
    displayName: 'Copy Maven authorization configuration to Maven home directory'

    # Exports otpVersion as pipeline variable
  - bash: docker-build/azure-deploy/git-version.sh
    displayName: 'Calculate next version and tag Git commit'
    env:
      DEVOPS_ACCESSTOKEN: $(System.AccessToken)
      SOURCE_BRANCH: $(Build.SourceBranch)

#  - task: Maven@3
#    displayName: 'Publish artifact with version number to Skånetrafiken Maven repository'
#    inputs:
#      goals: 'clean package deploy'
#      options: '-Pjunit-report --settings docker-build/azure-deploy/settings.xml -Dsettings.security=/tmp/settings-security.xml -B -U'
#      jdkVersionOption: '1.11'
#      jdkArchitectureOption: 'x64'
#      mavenOptions: '-Xmx1G' # Build agents are limited to 2Gb
#
#  - task: PublishCodeCoverageResults@1
#      inputs:
#        codeCoverageTool: 'JaCoCo'
#        reportDirectory: $(System.DefaultWorkingDirectory)/target/site/jacoco-ut/**/*.*
#        summaryFileLocation: $(System.DefaultWorkingDirectory)/target/site/jacoco-ut/jacoco.xml

  # Trigger deploy
  - task: TriggerBuild@3
    inputs:
      definitionIsInCurrentTeamProject: true
      buildDefinition: 'resesok-otp'
      queueBuildForUserThatTriggeredBuild: true
      ignoreSslCertificateErrors: false
      useSameSourceVersion: false
      useCustomSourceVersion: false
      useSameBranch: true
      waitForQueuedBuildsToFinish: false
      storeInEnvironmentVariable: false
      authenticationMethod: 'OAuth Token'
      enableBuildInQueueCondition: false
      dependentOnSuccessfulBuildCondition: false
      dependentOnFailedBuildCondition: false
      checkbuildsoncurrentbranch: false
      failTaskIfConditionsAreNotFulfilled: false
      fetchFromNexus: true
      otpVersion: $(otpVersion)
