trigger: none
pool: 'TJP'

steps:
  - checkout: self
    persistCredentials: true
  # Look on SourceBranch and ensure that we can only merge from release branch
  # Otherwise exit with error code
  - bash: docker-build/azure-deploy/release-check.sh
    displayName: 'Validate source branch'
    env:
      SOURCE_BRANCH: $(System.PullRequest.SourceBranch)