version: 2
jobs:
  test:
    docker:
    - image: maven:3.5.4-jdk-8
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
    - checkout
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s .circleci/settings.xml
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    # Cannot use -o because of snapshot dependencies.
    - run: mvn test -s .circleci/settings.xml
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit
  deploy-nexus:
    docker:
    - image: maven:3.5.4-jdk-8
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
    - checkout
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s .circleci/settings.xml
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    # Cannot use -o because of snapshot dependencies.
    - run: mvn deploy -s .circleci/settings.xml -DskipTests
  notify-build:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    steps:
    - run:
        name: Notify about build and nexus updated
        command: |
            echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
            echo 'export BUILD_STATUS_API_KEY="$BUILD_STATUS_API_KEY"' >> $BASH_ENV
            /tools/build_notify.sh
        environment:
          CIRCLE_PROJECT_REPONAME: otp
workflows:
  version: 2
  build_test_deploy:
    jobs:
    - test:
        context: org-carbon
        filters:
          branches:
            only: rutebanken_develop
    - deploy-nexus:
        context: org-carbon
        requires:
        - test
        filters:
          branches:
            only: rutebanken_develop
    - notify-build:
        context: org-carbon
        requires:
        - deploy-nexus
        filters:
          branches:
            only: rutebanken_develop