apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  applicationInsightsKey: {{ .Values.applicationInsightsKey | b64enc }}
  STORAGE_ACCOUNT_NAME: {{ .Values.STORAGE_ACCOUNT_NAME | b64enc }}
  TJPSAGEO_AZURE_BLOB_STORAGE_KEY: {{ .Values.TJPSAGEO_AZURE_BLOB_STORAGE_KEY | b64enc }}
