apiVersion: v1
name: otp
version: 'release-1.0.46'
appVersion: 'release-1.0.46'
description: Open Trip Planner
keywords:
- otp
sources:
- https://github.com/entur/opentripplanner
maintainers:
- name: 'team-ror'
  email: team.rutedata@entur.org
engine: gotpl
