env: dev-c2

replicas: 4

horizontalPodAutoscaler:
  enabled: true
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

rollingUpdate:
  maxSurge: 3
  maxUnavailable: 1

environmentValues:
  mardukGcpBaseName: "gs://marduk/"

cronjobRedeployOtp:
  environmentValues:
    cloudsdkCoreProject: carbon-1287

secretMounts:
  - name: marduk-key
    mountPath: /etc/marduk/marduk-blobstore-credentials.json
    subPath: marduk-blobstore-credentials.json
    secretName: marduk-carbon-storage-key
    readOnly: true







