env: production-c2

replicas: 5

horizontalPodAutoscaler:
  enabled: true
  maxReplicas: 65
  targetCPUUtilizationPercentage: 70

rollingUpdate:
  maxSurge: 5
  maxUnavailable: 3

environmentValues:
  mardukGcpBaseName: "gs://marduk-production/"

cronjobRedeployOtp:
  environmentValues:
    cloudsdkCoreProject: neon-1287

secretMounts:
  - name: marduk-key
    mountPath: /etc/marduk/marduk-blobstore-credentials.json
    subPath: marduk-blobstore-credentials.json
    secretName: marduk-neon-storage-key
    readOnly: true