env: production-c2

replicas: 20

horizontalPodAutoscaler:
  enabled: true
  maxReplicas: 65
  minReplicas: 10
  targetCPUUtilizationPercentage: 90

rollingUpdate:
  maxSurge: 5
  maxUnavailable: 1

environmentValues:
  mardukGcpBaseName: "gs://marduk-production/"
  googleApplicationCredentialsPath: /etc/gcs/otp-realtime-pubsub.json

cronjobRedeployOtp:
  environmentValues:
    cloudsdkCoreProject: neon-1287

cronjobRedeployGraphBuilder:
  mardukBucket: marduk-production
  mardukStorageSecretName: marduk-neon-storage-key

secretMounts:
  - name: marduk-key
    mountPath: /etc/marduk/marduk-blobstore-credentials.json
    subPath: marduk-blobstore-credentials.json
    secretName: marduk-neon-storage-key
    readOnly: true
  - name: otp-realtime-pubsub-key
    mountPath: /etc/gcs/otp-realtime-pubsub.json
    subPath: otp-realtime-pubsub.json
    secretName: otp-realtime-pubsub-key
    readOnly: true

configuration:
  siriVMUpdater: https://api.entur.io/realtime/v1/services
  siriETUpdater: https://api.entur.io/realtime/v1/services
  siriSXUpdater: https://api.entur.io/realtime/v1/services?maxSize=50
  useFlexService: true
  siriETPubsubUpdater:
    enabled: true
    googleProjectName: neon-1287
    pubsubTopicName: protobuf.estimated_timetables
    dataInitializationUrl: https://api.entur.io/realtime/v1/rest/et-monitored
