env: staging-c2

replicas: 3

horizontalPodAutoscaler:
  enabled: true
  maxReplicas: 40
  minReplicas: 2
  targetCPUUtilizationPercentage: 90

rollingUpdate:
  maxSurge: 3
  maxUnavailable: 1

environmentValues:
  mardukGcpBaseName: "gs://marduk-stage/"
  googleApplicationCredentialsPath: /etc/gcs/otp-realtime-pubsub.json

cronjobRedeployOtp:
  environmentValues:
    cloudsdkCoreProject: radon-1287

cronjobRedeployGraphBuilder:
  mardukBucket: marduk-stage
  mardukStorageSecretName: marduk-radon-storage-key

secretMounts:
  - name: marduk-key
    mountPath: /etc/marduk/marduk-blobstore-credentials.json
    subPath: marduk-blobstore-credentials.json
    secretName: marduk-radon-storage-key
    readOnly: true
  - name: otp-realtime-pubsub-key
    mountPath: /etc/gcs/otp-realtime-pubsub.json
    subPath: otp-realtime-pubsub.json
    secretName: otp-realtime-pubsub-key
    readOnly: true

configuration:
  siriVMUpdater: https://api.staging.entur.io/realtime/v1/services
  siriETUpdater: https://api.staging.entur.io/realtime/v1/services
  siriSXUpdater: https://api.staging.entur.io/realtime/v1/services?maxSize=50
  useFlexService: true
  siriETPubsubUpdater:
    enabled: true
    googleProjectName: radon-1287
    pubsubTopicName: protobuf.estimated_timetables
    dataInitializationUrl: https://api.staging.entur.io/realtime/v1/rest/et-monitored
