name: OTP CI Build
# On [push, pull_request] causes double-builds when creating PRs.
# But triggering on push only will miss pull requests from outside authors.
on:
  # Should catch merged pull requests, pushes to Conveyal PR branches, and tags.
  # The push event's ref reveals the branch name for S3 upload, unlike pull_request which sees the merge target.
  push
  # Try to catch PRs from outside authors, which don't need to be uploaded to S3.
  # pull_request:
  #   branches:
  #     - dev
#     - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Starting in v2.2 checkout action fetches all tags when fetch-depth=0, for auto-versioning.
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      # Java setup step completes very fast, no need to run in a preconfigured docker container
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.m2
          key: maven-local-repo
      - name: Build and Test
        run: mvn --batch-mode --update-snapshots package
